<!doctype html>
<html lang="en">
<head>

	<title>Cloud Dev Exercise 024 - Writing user defined functions</title>
	<meta charset="utf-8">

</head>
<body>

<h1>Writing user defined functions</h1>

<p>Open this file in a browser but edit /ex024/includes/functions.php</p>


<!-- **********************************************************************************
*                                    Exercise 024a                                    *
*********************************************************************************** -->
<h2>024a Converting HEX color to RGB</h2>

<!--
Do not edit this file - edit /ex024/includes/functions.php
-->

<?php
/* Open the file /ex024/includes/functions.php and write a function as directed in the 
comments. The code in this page will help you test that your function is working 
correctly.
*/

$colorA = "#ff0000";
$colorB = "#993366";
$colorC = "#009999";

$rgbA = hex_to_rgb($colorA);
$rgbB = hex_to_rgb($colorB);
$rgbC = hex_to_rgb($colorC);

var_dump ($rgbA);
var_dump ($rgbB);
var_dump ($rgbC);

echo "<p><span style=\"color:$colorA;\">This colour in hex $colorA</span><br>\n";
echo "<span style=\"color:rgba({$rgbA['red']}, {$rgbA['green']},{$rgbA['blue']}, 1);\">
should match this colour in RGB 
rgba({$rgbA['red']}, {$rgbA['green']}, {$rgbA['blue']}, 1)</span></p>\n";

echo "<p><span style=\"color:$colorB;\">This colour in hex $colorB</span><br>\n";
echo "<span style=\"color:rgba({$rgbB['red']}, {$rgbB['green']},{$rgbB['blue']}, 1);\">
should match this colour in RGB 
rgba({$rgbB['red']}, {$rgbB['green']}, {$rgbB['blue']}, 1)</span></p>\n";

echo "<p><span style=\"color:$colorC;\">This colour in hex $colorC</span><br>\n";
echo "<span style=\"color:rgba({$rgbC['red']}, {$rgbC['green']},{$rgbC['blue']}, 1);\">
should match this colour in RGB 
rgba({$rgbC['red']}, {$rgbC['green']}, {$rgbC['blue']}, 1)</span></p>\n";

?>

</body>
</html>