<!doctype html>
<html lang="en">
<head>

	<title>Cloud Dev Exercise 023 - Writing user defined functions</title>
	<meta charset="utf-8">

</head>
<body>

<h1>Writing user defined functions</h1>

<p>Open this file in a browser but edit /ex023/includes/functions.php</p>

<!-- **********************************************************************************
*                                    Exercise 023a                                    *
*********************************************************************************** -->
<h2>023a Checking for values in two arrays</h2>

<!--
Do not edit this file - edit /ex023/includes/functions.php

NOTE: You will need to "include" the function.php file at the top of this page - this was
done for you in previous exercises but now you need to remember to do it yourself.
-->

<?php
/* Open the file /ex023/includes/functions.php and write a function as directed in the 
comments. The code in this page will help you test that your function is working 
correctly.
*/

$ateam = array ("Bob", "Jane", "Susan", "Amy", "Frank", "Eric", "Donald");
$bteam = array ("Jane", "Nigel", "Norman", "Eric", "Donald", "Thomas");
$cteam = array ("Mary", "Beth", "David", "Mike", "Nigel", "Ernie");

// Check who is in teams A & B - (Jane, Eric, Donald)
if ($bothAandB = in_both_arrays ($ateam, $bteam)) {
	echo "<p>People in teams A and B</p>\n";
	echo "<ol>\n";
	foreach ($bothAandB as $member) {
		echo "<li>$member</li>\n";
	}
	echo "</ol>\n";
} else {
	echo "<p>No matches in Team A and Team B</p>\n";
}

// Check who is in teams B & C - (Nigel)
if ($bothBandC = in_both_arrays ($bteam, $cteam)) {
	echo "<p>People in teams B and C</p>\n";
	echo "<ol>\n";
	foreach ($bothBandC as $member) {
		echo "<li>$member</li>\n";
	}
	echo "</ol>\n";
} else {
	echo "<p>No matches in Team B and Team C</p>\n";
}

// Check who is in all teams- (no match)
if ($allTeams = in_both_arrays (in_both_arrays ($ateam, $ateam), $cteam)){
	echo "<p>People in all teams</p>\n";
	echo "<ol>\n";
	foreach ($allTeams as $member) {
		echo "<li>$member</li>\n";
	}
	echo "</ol>\n";
} else {
	echo "<p>No matches in all teams</p>\n";
}
?>

</body>
</html>