<!doctype html>
<html lang="en">
<head>

	<title>Cloud Dev Exercise 025 - Writing user defined functions</title>
	<meta charset="utf-8">

</head>
<body>

<h1>Writing user defined functions</h1>

<p>Open this file in a browser but edit /ex025/includes/functions.php</p>

<!-- **********************************************************************************
*                                    Exercise 025a                                    *
*********************************************************************************** -->
<h2>025a Checking if one number within range of another</h2>

<!--
Do not edit this file - edit /ex025/includes/functions.php
-->

<?php
/* Open the file /ex025/includes/functions.php and write a function as directed in the 
comments. The code in this page will help you test that your function is working 
correctly.
*/
$a = 10;
$b = 8;
$c = 30;

if (in_range ($a, $b, $c)) {
	echo "<p>$b is within $c% of $a.</p>\n";
} else {
	echo "<p>$b is not within $c% of $a.</p>\n";
}

$d = 1000;
$e = 725;
$f = 25;

if (in_range ($d, $e, $f)) {
	echo "<p>$e is within $f% of $d.</p>\n";
} else {
	echo "<p>$e is not within $f% of $d.</p>\n";
}

$g = 17.25;
$h = 17.84;
$i = 1.2;

if (in_range ($g, $h, $i)) {
	echo "<p>$h is within $i% of $g.</p>\n";
} else {
	echo "<p>$h is not within $i% of $g.</p>\n";
}

?>

</body>
</html>